name: k6 Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run smoke test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/smoke.js
